language: node_js
node_js:
  - "12.4.0"
branches:
  only: 
    - master
    - /^greenkeeper/.*$/
script:
  - yarn build
  - yarn docs
  - yarn docs:extra

deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master